title: ALL POSTS ğŸ“–
description: joker Record life ğŸ¬
author: joker
github: https://github.com/Joker-j-o
about: ã€ŒBin&Web Security Researcherã€
avatar_url: /static/img/1012576.jpg

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    - icon: fa-facebook
      link: "#"
    - icon: fa-twitter
      link: "#"
    - icon: fa-linkedin
      link: "#"
    - icon: fa-stack-exchange
      link: "#"
    - icon: fa-github
      link: "https://github.com/Joker-j-o"
    - icon: fa-csdn
      link: "https://blog.csdn.net/weixin_43400271"

urls:
    - text: About Me ğŸ‘ˆ
      url: /about/
    - text: Tags ğŸ“
      url: /category/security
    - text: XML Feed ğŸ§¾
      url: /feed.xml

url: "https://ctf.dog"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
kramdown:
    input:  GFM
gems:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']
