title: ALL POSTS ğŸ“–
description: Bree Record life ğŸ¬
author: Bree
github: https://github.com/Joker-j-o
# about: ã€Œjoker&Web Security Researcherã€
about: ã€Œ Bree & Web Python after end ã€
avatar_url: /static/img/1012576.jpg

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    - icon: fa-facebook
      link: "https://joker-j-o.github.io/"
    - icon: fa-twitter
      link: "https://joker-j-o.github.io/"
    - icon: fa-linkedin
      link: "https://joker-j-o.github.io/"
    - icon: fa-stack-exchange
      link: "https://blog.csdn.net/weixin_43400271"
    - icon: fa-github
      link: "https://github.com/Joker-j-o"

urls:
    - text: About Me ğŸ‘ˆ
      url: /about/
    - text: Tags ğŸ“
      url: /category/security
    - text: XML Feed ğŸ§¾
      url: /feed.xml
    - text: TOOLS
      url: https://devhints.io/

url: "https://joker-j-o.github.io"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
kramdown:
    input:  GFM
gems:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']


# Featured Tags
featured-tags: true                     # æ˜¯å¦ä½¿ç”¨é¦–é¡µæ ‡ç­¾
featured-condition-size: 0              # ç›¸åŒæ ‡ç­¾æ•°é‡å¤§äºè¿™ä¸ªæ•°ï¼Œæ‰ä¼šå‡ºç°åœ¨é¦–é¡µ å¦‚æœå°†sizeæ”¹ä¸º0 é‚£ä¹ˆåªæœ‰ä¸€ä¸ªä¹Ÿä¼šæ˜¾ç¤º